INT_PRODUCTS = {
    "product_id": "VARCHAR",
    "source": "VARCHAR",
    "brand": "VARCHAR",
    "product_name": "VARCHAR",
    "product_type": "VARCHAR",
    "variant": "VARCHAR",
    "quantity": "DECIMAL(12,4)",
    "quantity_unit": "VARCHAR",
    "price_cad": "DECIMAL(10,2)",
    "image_url": "VARCHAR",
    "category": "VARCHAR",
    "is_available": "BOOLEAN",
    "scraped_at": "VARCHAR",
}

INT_NUTRITION = {
    "product_id": "VARCHAR",
    "source": "VARCHAR",
    "serving_size": "VARCHAR",
    "calories": "INTEGER",
    "fat_g": "DECIMAL(8,2)",
    "saturated_fat_g": "DECIMAL(8,2)",
    "trans_fat_g": "DECIMAL(8,2)",
    "cholesterol_mg": "DECIMAL(8,2)",
    "sodium_mg": "DECIMAL(8,2)",
    "potassium_mg": "DECIMAL(8,2)",
    "carbohydrate_g": "DECIMAL(8,2)",
    "fibre_g": "DECIMAL(8,2)",
    "sugars_g": "DECIMAL(8,2)",
    "protein_g": "DECIMAL(8,2)",
    "calcium_mg": "DECIMAL(8,2)",
    "iron_mg": "DECIMAL(8,2)",
    "polyunsaturated_fat_g": "DECIMAL(8,2)",
    "monounsaturated_fat_g": "DECIMAL(8,2)",
    "omega6_g": "DECIMAL(8,2)",
    "omega3_g": "DECIMAL(8,2)",
    "sugar_alcohols_g": "DECIMAL(8,2)",
    "scraped_at": "VARCHAR",
}

INT_PARSED_QUANTITIES = {
    "product_id": "VARCHAR",
    "source": "VARCHAR",
    "raw_size_text": "VARCHAR",
    "quantity_raw": "DECIMAL(12,4)",
    "quantity_ml": "DECIMAL(12,4)",
    "quantity_g": "DECIMAL(12,4)",
    "quantity_unit_normalized": "VARCHAR",
    "pack_count": "INTEGER",
    "pack_unit": "VARCHAR",
}
