NUTRITIONAL_SCHEMA = {
    "product_id": "VARCHAR",
    "retailer_product_id": "VARCHAR",
    "serving_size": "VARCHAR",
    "calories": "INTEGER",
    "fat_g": "DECIMAL(8,2)",
    "fat_daily_pct": "DECIMAL(5,1)",
    "saturated_fat_g": "DECIMAL(8,2)",
    "saturated_fat_daily_pct": "DECIMAL(5,1)",
    "trans_fat_g": "DECIMAL(8,2)",
    "polyunsaturated_fat_g": "DECIMAL(8,2)",
    "monounsaturated_fat_g": "DECIMAL(8,2)",
    "omega6_g": "DECIMAL(8,2)",
    "omega3_g": "DECIMAL(8,2)",
    "carbohydrate_g": "DECIMAL(8,2)",
    "carbohydrate_daily_pct": "DECIMAL(5,1)",
    "fibre_g": "DECIMAL(8,2)",
    "fibre_daily_pct": "DECIMAL(5,1)",
    "sugars_g": "DECIMAL(8,2)",
    "sugars_daily_pct": "DECIMAL(5,1)",
    "sugar_alcohols_g": "DECIMAL(8,2)",
    "protein_g": "DECIMAL(8,2)",
    "cholesterol_mg": "DECIMAL(8,2)",
    "sodium_mg": "DECIMAL(8,2)",
    "sodium_daily_pct": "DECIMAL(5,1)",
    "potassium_mg": "DECIMAL(8,2)",
    "potassium_daily_pct": "DECIMAL(5,1)",
    "calcium_mg": "DECIMAL(8,2)",
    "calcium_daily_pct": "DECIMAL(5,1)",
    "iron_mg": "DECIMAL(8,2)",
    "iron_daily_pct": "DECIMAL(5,1)",
    "scraped_at": "TIMESTAMP",
}

NUTRITIONAL_NUTRIENTS = [
    "calories", "fat", "saturated_fat", "trans_fat",
    "polyunsaturated_fat", "monounsaturated_fat", "omega6", "omega3",
    "carbohydrate", "fibre", "sugars", "sugar_alcohols",
    "protein", "cholesterol", "sodium",
    "potassium", "calcium", "iron",
]
