STG_COMPLIMENTS_PRODUCTS = {
    "product_id": "VARCHAR",
    "retailer_product_id": "VARCHAR",
    "slug": "VARCHAR",
    "product_name": "VARCHAR",
    "brand": "VARCHAR",
    "price_cad": "DECIMAL(10,2)",
    "price_currency": "VARCHAR",
    "size": "VARCHAR",
    "category": "VARCHAR",
    "image_url": "VARCHAR",
    "is_available": "BOOLEAN",
    "source": "VARCHAR",
    "source_url": "VARCHAR",
    "source_type": "VARCHAR",
    "scraped_at": "VARCHAR",
}

STG_SOBEYS_PRODUCTS = {
    "sku": "VARCHAR",
    "sobeys_url": "VARCHAR",
    "brand": "VARCHAR",
    "product_name": "VARCHAR",
    "description": "VARCHAR",
    "image_url": "VARCHAR",
    "price": "DECIMAL(10,2)",
    "price_currency": "VARCHAR",
    "availability": "VARCHAR",
    "source": "VARCHAR",
    "scraped_at": "VARCHAR",
}

STG_NUTRITION_VOILA = {
    "product_id": "VARCHAR",
    "retailer_product_id": "VARCHAR",
    "serving_size": "VARCHAR",
    "calories": "INTEGER",
    "fat_g": "DECIMAL(8,2)",
    "saturated_fat_g": "DECIMAL(8,2)",
    "trans_fat_g": "DECIMAL(8,2)",
    "polyunsaturated_fat_g": "DECIMAL(8,2)",
    "monounsaturated_fat_g": "DECIMAL(8,2)",
    "omega6_g": "DECIMAL(8,2)",
    "omega3_g": "DECIMAL(8,2)",
    "carbohydrate_g": "DECIMAL(8,2)",
    "fibre_g": "DECIMAL(8,2)",
    "sugars_g": "DECIMAL(8,2)",
    "sugar_alcohols_g": "DECIMAL(8,2)",
    "protein_g": "DECIMAL(8,2)",
    "cholesterol_mg": "DECIMAL(8,2)",
    "sodium_mg": "DECIMAL(8,2)",
    "potassium_mg": "DECIMAL(8,2)",
    "calcium_mg": "DECIMAL(8,2)",
    "iron_mg": "DECIMAL(8,2)",
    "scraped_at": "VARCHAR",
}

STG_NUTRITION_SOBEYS = {
    "product_id": "VARCHAR",
    "sobeys_url": "VARCHAR",
    "serving_size": "VARCHAR",
    "calories": "INTEGER",
    "fat_g": "DECIMAL(8,2)",
    "saturated_fat_g": "DECIMAL(8,2)",
    "trans_fat_g": "DECIMAL(8,2)",
    "cholesterol_mg": "DECIMAL(8,2)",
    "sodium_mg": "DECIMAL(8,2)",
    "potassium_mg": "DECIMAL(8,2)",
    "carbohydrate_g": "DECIMAL(8,2)",
    "fibre_g": "DECIMAL(8,2)",
    "sugars_g": "DECIMAL(8,2)",
    "protein_g": "DECIMAL(8,2)",
    "calcium_mg": "DECIMAL(8,2)",
    "iron_mg": "DECIMAL(8,2)",
    "scraped_at": "VARCHAR",
}
